services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: todo-backend

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    container_name: todo-frontend
    depends_on:
      - backend
